### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by Slahser** [toolinbox/iPic#1]
1. 状态栏 icon 第一次启动的时候会覆盖其他选项,比如 help..这个我也没复现出来 
2. 设置窗口总是保持最前... 
3. 七牛 http prefix 不支持文件夹比如 http://xxx/image/ 
4. 七牛 修改 http prefix 之后(从 http 修改到 https),点击 apply 之后并未直接生效,需要程序重启.

**Comment by atjason** [comment]
@Slahser 感谢反馈

1. 这是系统行为；如果启动是菜单栏已经很拥挤就会这样，换其它的 App 也会有这样的问题。
2. 故意这样的，因为设置窗口没有 Dock 图标，很容易被盖住后找不到；而且一旦设置就会关闭，所以影响不大吧？
3. 这个确实还不支持，记下了。
4. 其实不需要重启程序，在菜单中先选择默认、再选择新创建的七牛即可。不过还是可以改进，记下了。

**Comment by atjason** [comment]
@Slahser 之前反馈的这两个问题，在最新版中已经解决了，可以下载试试：
[](https://github.com/toolinbox/iPic/raw/master/release/iPic_v0.7.6.dmg)

_七牛 http prefix 不支持文件夹比如 http://xxx/image/_
_七牛 修改 http prefix 之后(从 http 修改到 https),点击 apply 之后并未直接生效,需要程序重启._

**Comment by Slahser** [comment]
已经体验,满足我所有需求~支持.期待早日上架


提需求的话:

1.可以做成图片拖到icon上弹出一个dropshelf那样的小框来代表上传区域.现在自动上传不太友好


On June 12, 2016 at 06:57:01, Jason (notifications@github.com) wrote:

@Slahser <https://github.com/Slahser> 之前反馈的这两个问题，在最新版中已经解决了，可以下载试试：
<https://github.com/toolinbox/iPic/raw/master/release/iPic_v0.7.6.dmg>

*七牛 http prefix 不支持文件夹比如 http://xxx/image/ <http://xxx/image/>*
*七牛 修改 http prefix 之后(从 http 修改到 https),点击 apply 之后并未直接生效,需要程序重启.*

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/toolinbox/iPic/issues/1#issuecomment-225399029>, or mute
the thread
<https://github.com/notifications/unsubscribe/ADliaCEhcm0t8d3D77MOpPRq2Yg9S8OQks5qKz09gaJpZM4Im2OY>
.

-- 
S1ahs3r
Sent with Airmail.

**Comment by atjason** [comment]
@Slahser 恩，这个交互在计划中的。感谢支持、感谢反馈。

**Comment by toolinbox** [comment]
@Slahser 反馈的 3、4 已解决，关闭这个 issue.
