### ISSUE TITLE
小图标能不能改成静态图，不要闪，或者增加个选项。

### ISSUE THREAD

**Issue by zanderzhng** [toolinbox/iPic#2]
我在 Bartender 里设置的，有变化就显示5秒，没变化就隐藏。
iPic 右下角有个不停的闪的点，Bartender 限制不住。

**Comment by toolinbox** [comment]
您好，在菜单中停止 自动上传 应该就可以了。

闪烁是为了提醒自己当前是自动上传模式，避免图片被误传。

**Comment by toolinbox** [comment]
@zanderzhng 我测试了停止 自动上传 后，就可以正常隐藏到 Bartender 中，您试试？

**Comment by zanderzhng** [comment]
我想保留自动上传....  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On May 26 2016, at 12:07 pm, Toolinbox &lt;notifications@github.com&gt; wrote:  

> [@zanderzhng](https://github.com/zanderzhng) 我测试了停止 自动上传 后，就可以正常隐藏到
Bartender 中，您试试？

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/toolinb
ox/iPic/issues/2#issuecomment-221772557)![](https://github.com/notifications/b
eacon/AA09pTPVqNA6uYSMJWGh9QLkJgbjSMSlks5qFRxxgaJpZM4InD5O.gif)

**Comment by toolinbox** [comment]
@zanderzhng 这个 ... 就是因为很多用户提开了之后忘了关，导致误传图片，才加了这个小提示的，短期应该不会去掉，不然又要被骂太随性了，理解下...

**Comment by toolinbox** [comment]
@zanderzhng 目前最新体验版已经去掉自动上传，图标也不会闪了。关闭此 issue
