### ISSUE TITLE
建议增加一个上传当前粘贴板图片的快捷方式

### ISSUE THREAD

**Issue by joway** [toolinbox/iPic#3]
场景:
在全屏间切换工作时，不是很情愿去点击状态栏，希望加个快捷键，可以直接把当前粘贴板的截图上传到图床去，这样几乎就可以不去理会状态栏啦 ~

**Comment by atjason** [comment]
你好，
目前是支持快捷键的。虽然不能一步到位，但也差不多能满足你的需求：

1. 按下全局快捷键 "Command + Shift + E" 呼出 iPic 菜单。当然，快捷键可以在 iPic 中自定义
2. 出现 iPic 菜单中，按数字1、2、3 ... 就可以自动上传粘贴板中的图片

这样，你甚至可以隐藏 iPic 的状态栏图标了。

**Comment by atjason** [comment]
@joway iPic 最新体验版已经支持使用快捷键直接把当前粘贴板的截图上传到图床去，还有其他一些改进，了解更多及下载：http://v2ex.com/t/296218

**Comment by toolinbox** [comment]
@joway 最新体验版已经支持 Command + Shift + U 来上传粘贴板中的截图。关闭此 issue.
