### ISSUE TITLE
文件名有括号时复制的路径无法访问

### ISSUE THREAD

**Issue by yangg** [toolinbox/iPic#4]
文件名为 `border-(1).gif`
配置的qiniu

**Comment by yangg** [comment]
另外希望可以按两次 cmd + c 来触发上传并复制链接

**Comment by atjason** [comment]
这个问题已经解决了，目前支持这样任性的文件名：~!@#$%^&*()_+`-=[]\{}|;,./< >?'".jpg 下个体验版本就会包含这一修改。

"按两次 cmd + c 来触发上传并复制链接" 这个也记下了，感谢反馈~

**Comment by atjason** [comment]
@yangg 最新版已经解决文件名中有特殊字符的问题了，[下载试试吧](https://github.com/toolinbox/iPic/raw/master/release/iPic_v0.7.6.dmg)
