### ISSUE TITLE
能否做到Mac里右键菜单“用iPic上传”的快捷方式，而不是复制图片

### ISSUE THREAD

**Issue by gzelvis** [toolinbox/iPic#5]
如果你有装Dropbox，对图片点鼠标右键后，会有一个“移动到Dropbox”的选项。目前iPic复制了就自动上传，但有时候其实我只是想复制到硬盘的其它文件夹，你知道微博图片上传后是没办法彻底删除的，我知道iPic有一个“自动上传”的开关，但这个有时候忘记删就惨了。所以最好还是能做一个鼠标右键像是“移动到Dropbox”这样一个功能菜单“通过iPic上传“ 而不是简单监听复制图片

**Comment by atjason** [comment]
@gzelvis 你说的是在 Finder 中右击图片文件后，在“服务”菜单中增加类似“通过 iPic 上传”这样的菜单项对吧？恩，这个是在计划中的，后续的版本就会增加。

另外，还会考虑增加将图片拖放至菜单栏图标时自动上传。

感谢你的反馈，期待更多建议 :)

**Comment by gzelvis** [comment]
辛苦，祝软件越做越好！

发送自 Elvis Yao 的 iPhone




On Sun, Jun 12, 2016 at 6:55 AM +0800, "Jason" <notifications@github.com> wrote:












@gzelvis 你说的是在 Finder 中右击图片文件后，在“服务”菜单中增加类似“通过 iPic 上传”这样的菜单项对吧？恩，这个是在计划中的，后续的版本就会增加。



另外，还会考虑增加将图片拖放至菜单栏图标时自动上传。



感谢你的反馈，期待更多建议 :)

**Comment by atjason** [comment]
@gzelvis 哇，反应神速！

**Comment by gzelvis** [comment]
为自己做事情的人，恨不得光速

发送自 Elvis Yao 的 iPhone




On Sun, Jun 12, 2016 at 6:59 AM +0800, "Jason" <notifications@github.com> wrote:












@gzelvis 哇，反应神速！

**Comment by atjason** [comment]
@gzelvis 深有同感

**Comment by gzelvis** [comment]
你的菜单图标底是白色的，字体又细，效果不好，建议参考Producthunt的Mac版logo

发送自 Elvis Yao 的 iPhone




On Sun, Jun 12, 2016 at 7:01 AM +0800, "Jason" <notifications@github.com> wrote:












@gzelvis 深有同感

**Comment by atjason** [comment]
@gzelvis 恩，收到，感谢建议。

**Comment by toolinbox** [comment]
@gzelvis 目前 iPic 已经支持在 Finder 中右击图片文件后，在“服务”菜单中“通过 iPic 上传”；另外，也支持将图片拖放至菜单栏图标时自动上传。关闭这个 issue
